In [187]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics.pairwise import euclidean_distances

In [112]:
movie_genre = pd.read_csv("ProcessedData/movie_genre.csv")
indexedMovies = pd.read_csv("ProcessedData/indexedMovies.csv")

In [138]:
##Getting index based on titles of the movie
def get_movie_id(title):
    return indexedMovies.loc[indexedMovies['Title']==title].values.tolist()[0][0]

In [141]:
##Getting suggestions by title name
def get_suggestion_by_movie_title(title):
    movie_index = get_movie_id(title)-1
    return get_suggestion_by_movie_index(movie_index)

In [176]:
def get_suggestion_by_movie_id(movieId):
    movieId = int(movieId)
    return get_suggestion_by_movie_index(movieId-1)

In [130]:
##Getting Titles based on the indexes from the suggestions 
def get_suggestion_by_movie_index(index):
    row = enumerated[index]
    returnVal = []
    print("Given Movie", indexedMovies.loc[indexedMovies['MovieId'] == index+1].values.tolist()[0])
    for movies in row:
        returnVal.append(indexedMovies.loc[indexedMovies['MovieId'] == movies[0]+1].values.tolist()[0])
    return (returnVal)         

# User's top 3 rated movies

In [183]:
def get_movies_based_on_previous_rating(userId):
    userRatings = combinedRatings.loc[combinedRatings['UserId'] == userId, 'Ratings'].tolist()[0]
    movies = userRatings.split(' ')
    returnList = []
    for movie in movies:
        movieId,ratings = movie.strip().split('-')
        returnList+=get_suggestion_by_movie_id(movieId)
    return returnList

In [128]:
combinedRatings = pd.read_csv('processedData/combinedRatings/combinedRatings.csv', names = ['UserId','Ratings'])
combinedRatings.head(5)

UserId             Ratings
0      22   128-5 258-5 510-5
1     244    154-5 89-5 652-5
2     115     8-5 127-5 234-5
3     305    427-5 483-5 50-5
4     286  1014-5 379-5 288-5

In [182]:
a = [[1,0],[2,0],[3,0]]
print(euclidean_distances(a))


[[0. 1. 2.]
 [1. 0. 1.]
 [2. 1. 0.]]


# Finding Cosine Similarity between movies

In [110]:
columnValues = movie_genre.values
cs = cosine_similarity(columnValues)
cs

In [116]:
## Suggestion list for each movie by their indexes
enumerated = []

for index in cs:
    row = list(enumerate(index))
    row.sort(key = lambda x: -x[1])
    row = list(filter(lambda x: x[1]>0 , row))[1:6]
    enumerated.append(row)

enumerated = np.array(enumerated)

# Get Suggestions

In [131]:
suggestions = get_suggestion_by_movie_index(0)
for movies in suggestions:
    print(movies)

Given Movie [1, 'Toy Story (1995)']
[422, 'Aladdin and the King of Thieves (1996)']
[95, 'Aladdin (1992)']
[1219, 'Goofy Movie, A (1995)']
[63, 'Santa Clause, The (1994)']
[94, 'Home Alone (1990)']


In [139]:
get_movie_id("Aladdin and the King of Thieves (1996)")

422

In [142]:
get_suggestion_by_movie_title('Toy Story (1995)')

Given Movie [1, 'Toy Story (1995)']


[[422, 'Aladdin and the King of Thieves (1996)'],
 [95, 'Aladdin (1992)'],
 [1219, 'Goofy Movie, A (1995)'],
 [63, 'Santa Clause, The (1994)'],
 [94, 'Home Alone (1990)']]

In [184]:
get_movies_based_on_previous_rating(22)

Given Movie [128, 'Supercop (1992)']
Given Movie [258, 'Contact (1997)']
Given Movie [510, 'Magnificent Seven, The (1954)']


[[79, 'Fugitive, The (1993)'],
 [128, 'Supercop (1992)'],
 [144, 'Die Hard (1988)'],
 [147, 'Long Kiss Goodnight, The (1996)'],
 [226, 'Die Hard 2 (1990)'],
 [258, 'Contact (1997)'],
 [429, 'Day the Earth Stood Still, The (1951)'],
 [1006, 'Until the End of the World (Bis ans Ende der Welt) (1991)'],
 [239, 'Sneakers (1992)'],
 [270, 'Gattaca (1997)'],
 [840, 'Last Man Standing (1996)'],
 [177, 'Good, The Bad and The Ugly, The (1966)'],
 [339, 'Mad City (1997)'],
 [686, 'Perfect World, A (1993)'],
 [808, 'Program, The (1993)']]