In [33]:
from sklearn.metrics.pairwise import euclidean_distances
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd
import numpy as np
from sklearn.preprocessing import normalize

In [10]:
users = pd.read_csv('processedData/combinedUsers/combinedUsers.csv', names = ['UserId','Age','Gender','Occupation','Zip','AgeOc'])
users.head(5)

UserId  Age Gender  Occupation    Zip          AgeOc
0       1   24      M  technician  85711  24_technician
1       2   53      F       other  94043       53_other
2       3   23      M      writer  32067      23_writer
3       4   24      M  technician  43537  24_technician
4       5   33      F       other  15213       33_other

In [41]:
def get_user_index_by_user_id(user_id):
    return int(user_id-1)

In [39]:
def get_user_suggestions_by_user_id(user_id):
    userIndex = get_user_index_by_user_id(user_id)
    suggestion_index = updated_matrix[userIndex]
    print(suggestion_index)
    
    

In [42]:
get_user_suggestions_by_user_id(1)

[[  3.   2.]
 [455.   2.]
 [716.   2.]
 [831.   2.]
 [888.   2.]]


UserId    53
Name: 2, dtype: object

# Formatting Age-Occupation for cosine_sim


In [28]:
cv = CountVectorizer()

age_count_matrix = 1-euclidean_distances(users['Age'].values.reshape(-1,1))*0.01
age_count_matrix*0.6

array([[0.6  , 0.426, 0.594, ..., 0.576, 0.456, 0.588],
       [0.426, 0.6  , 0.42 , ..., 0.402, 0.57 , 0.414],
       [0.594, 0.42 , 0.6  , ..., 0.582, 0.45 , 0.594],
       ...,
       [0.576, 0.402, 0.582, ..., 0.6  , 0.432, 0.588],
       [0.456, 0.57 , 0.45 , ..., 0.432, 0.6  , 0.444],
       [0.588, 0.414, 0.594, ..., 0.588, 0.444, 0.6  ]])

In [30]:
occupation_count_matrix = cv.fit_transform(users['Occupation'])
# count_matrix.shape
ocs = cosine_similarity(occupation_count_matrix)
ocs*0.4

array([[0.4, 0. , 0. , ..., 0. , 0. , 0. ],
       [0. , 0.4, 0. , ..., 0. , 0. , 0. ],
       [0. , 0. , 0.4, ..., 0. , 0. , 0. ],
       ...,
       [0. , 0. , 0. , ..., 0.4, 0. , 0.4],
       [0. , 0. , 0. , ..., 0. , 0.4, 0. ],
       [0. , 0. , 0. , ..., 0.4, 0. , 0.4]])

In [34]:
age_occ_matrix = np.add(ocs,age_count_matrix)

In [36]:
updated_matrix = []
for rows in age_occ_matrix:
    row = list(enumerate(rows))
    row.sort(key= lambda x: -x[1])
    row = sorted(row,key=lambda x: -x[1])[1:6]
    updated_matrix.append(row)
updated_matrix = np.array(updated_matrix)

In [37]:
updated_matrix

array([[[  3.  ,   2.  ],
        [455.  ,   2.  ],
        [716.  ,   2.  ],
        [831.  ,   2.  ],
        [888.  ,   2.  ]],

       [[168.  ,   1.99],
        [135.  ,   1.98],
        [359.  ,   1.98],
        [488.  ,   1.98],
        [695.  ,   1.98]],

       [[292.  ,   1.99],
        [800.  ,   1.99],
        [ 21.  ,   1.98],
        [ 49.  ,   1.98],
        [444.  ,   1.98]],

       ...,

       [[ 98.  ,   2.  ],
        [116.  ,   2.  ],
        [138.  ,   2.  ],
        [273.  ,   2.  ],
        [313.  ,   2.  ]],

       [[941.  ,   2.  ],
        [ 87.  ,   1.99],
        [882.  ,   1.99],
        [610.  ,   1.98],
        [700.  ,   1.97]],

       [[303.  ,   2.  ],
        [326.  ,   2.  ],
        [358.  ,   2.  ],
        [360.  ,   2.  ],
        [376.  ,   2.  ]]])